# Configuration file for `prek`, a git hook framework written in Rust.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "check-added-large-files", args = ["--maxkb=512"] },
    { id = "check-case-conflict" },
    { id = "check-executables-have-shebangs" },
    { id = "check-json" },
    { id = "check-merge-conflict" },
    { id = "check-toml" },
    { id = "check-xml" },
    { id = "check-yaml" },
    { id = "debug-statements" },
    { id = "detect-private-key" },
    { id = "end-of-file-fixer" },
    { id = "mixed-line-ending" },
    { id = "check-shebang-scripts-are-executable" },
    { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.9"
hooks = [
    { id = "ruff", args = ["--fix", "--exit-non-zero-on-fix"] },
    { id = "ruff-format" },
]

[[repos]]
repo = "https://github.com/adamchainz/django-upgrade"
rev = "1.30.0"
hooks = [
    { id = "django-upgrade", args = ["--target-version", "5.2"] },
]

[[repos]]
repo = "https://github.com/asottile/pyupgrade"
rev = "v3.21.2"
hooks = [
    { id = "pyupgrade", args = ["--py313-plus"] },
]

[[repos]]
repo = "https://github.com/tox-dev/pyproject-fmt"
rev = "v2.21.0"
hooks = [
    { id = "pyproject-fmt" },
]

[[repos]]
repo = "https://github.com/abravalheri/validate-pyproject"
rev = "v0.25"
hooks = [
    { id = "validate-pyproject" },
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"
hooks = [
    { id = "actionlint" },
]
